Public Class Crosshair_selector
    Dim crosshair As String
    Private Sub btnConfirm_Click(sender As Object, e As EventArgs) Handles btnConfirm.Click
        Form1.globalcrosshair = crosshair
        Me.AutoScrollPosition = New Point(Math.Abs(Me.AutoScrollPosition.X), 0)
        MsgBox(crosshair)
        Me.Close()
    End Sub

    Private Sub picNone_Click(sender As Object, e As EventArgs) Handles picNone.Click
        crosshair = ""
        Me.Text = "Crosshair selector window - selected: NONE"
    End Sub

    Private Sub Crosshair_selector_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        Me.Location = New Point(Form1.Location.X - 250, Form1.Location.Y)
        Me.Size = New Size(828, 592)
    End Sub
    Private Sub Correction_Tick(sender As Object, e As EventArgs) Handles Correction.Tick
        If Me.AutoScrollPosition.Y < 0 Then
            Me.AutoScrollPosition = New Point(Math.Abs(Me.AutoScrollPosition.X), 0)
            Correction.Stop()
        End If
    End Sub
#Region "Crosshairs"

#End Region

    Private Sub picSchokk_Click_1(sender As Object, e As EventArgs) Handles picSchokk.Click
        crosshair = "cl_crosshair_drawoutline ""0""
cl_crosshair_dynamic_maxdist_splitratio ""0.35""
cl_crosshair_dynamic_splitalpha_innermod ""1""
cl_crosshair_dynamic_splitalpha_outermod ""0.5""
cl_crosshair_dynamic_splitdist ""7""
cl_crosshair_outlinethickness ""0.5""
cl_crosshair_sniper_width ""2""
cl_crosshairalpha ""300""
cl_crosshaircolor ""5""
cl_crosshaircolor_b ""0""
cl_crosshaircolor_g ""255""
cl_crosshaircolor_r ""0""
cl_crosshairdot ""0""
cl_crosshairgap ""-1""
cl_crosshairgap_useweaponvalue ""0""
cl_crosshairscale ""4""
cl_crosshairsize ""2.5""
cl_crosshairstyle ""4""
cl_crosshairthickness ""1""
cl_crosshairusealpha ""1""
cl_fixedcrosshairgap ""-4.5"""
        Me.Text = "Crosshair selector window - selected: Schokk"
    End Sub


    Private Sub picgobb_Click(sender As Object, e As EventArgs) Handles picgobb.Click
        crosshair = "cl_crosshair_drawoutline ""1""
cl_crosshair_dynamic_maxdist_splitratio ""0.35""
cl_crosshair_dynamic_splitalpha_innermod ""1""
cl_crosshair_dynamic_splitalpha_outermod ""0.5""
cl_crosshair_dynamic_splitdist ""7""
cl_crosshair_outlinethickness ""1""
cl_crosshair_sniper_width ""2""
cl_crosshairalpha ""255""
cl_crosshaircolor ""2""
cl_crosshaircolor_b ""0""
cl_crosshaircolor_g ""255""
cl_crosshaircolor_r ""0""
cl_crosshairdot ""0""
cl_crosshairgap ""0""
cl_crosshairgap_useweaponvalue ""0""
cl_crosshairscale ""4""
cl_crosshairsize ""2""
cl_crosshairstyle ""4""
cl_crosshairthickness ""1""
cl_crosshairusealpha ""1""
cl_fixedcrosshairgap ""-4.5"""
        Me.Text = "Crosshair selector window - selected: gob b"
    End Sub

    Private Sub picPtr_Click(sender As Object, e As EventArgs) Handles picPtr.Click
        crosshair = "cl_crosshair_drawoutline ""0""
cl_crosshair_dynamic_maxdist_splitratio ""0.35""
cl_crosshair_dynamic_splitalpha_innermod ""1""
cl_crosshair_dynamic_splitalpha_outermod ""0.5""
cl_crosshair_dynamic_splitdist ""7""
cl_crosshair_outlinethickness ""1""
cl_crosshair_sniper_width ""2""
cl_crosshairalpha ""255""
cl_crosshaircolor ""4""
cl_crosshaircolor_b ""255""
cl_crosshaircolor_g ""0""
cl_crosshaircolor_r ""255""
cl_crosshairdot ""0""
cl_crosshairgap ""-1""
cl_crosshairgap_useweaponvalue ""0""
cl_crosshairscale ""4""
cl_crosshairsize ""2""
cl_crosshairstyle ""4""
cl_crosshairthickness ""1""
cl_crosshairusealpha ""1""
cl_fixedcrosshairgap ""-4.5"""
        Me.Text = "Crosshair selector window - selected: ptr"
    End Sub

    Private Sub picLEGIJA_Click(sender As Object, e As EventArgs) Handles picLEGIJA.Click
        crosshair = "cl_crosshair_drawoutline ""1""
cl_crosshair_dynamic_maxdist_splitratio ""0.35""
cl_crosshair_dynamic_splitalpha_innermod ""1""
cl_crosshair_dynamic_splitalpha_outermod ""0.5""
cl_crosshair_dynamic_splitdist ""7""
cl_crosshair_outlinethickness ""1""
cl_crosshair_sniper_width ""2""
cl_crosshairalpha ""255""
cl_crosshaircolor ""5""
cl_crosshaircolor_b ""255""
cl_crosshaircolor_g ""0""
cl_crosshaircolor_r ""255""
cl_crosshairdot ""0""
cl_crosshairgap ""-1""
cl_crosshairgap_useweaponvalue ""0""
cl_crosshairscale ""4""
cl_crosshairsize ""1""
cl_crosshairstyle ""4""
cl_crosshairthickness ""0.5""
cl_crosshairusealpha ""1""
cl_fixedcrosshairgap ""-4.5"""
        Me.Text = "Crosshair selector window - selected: LEGIJA"
    End Sub

    Private Sub pictabseN_Click(sender As Object, e As EventArgs) Handles pictabseN.Click
        crosshair = "cl_crosshair_drawoutline ""0""
cl_crosshair_dynamic_maxdist_splitratio ""0.35""
cl_crosshair_dynamic_splitalpha_innermod ""1""
cl_crosshair_dynamic_splitalpha_outermod ""0.5""
cl_crosshair_dynamic_splitdist ""7""
cl_crosshair_outlinethickness ""1""
cl_crosshair_sniper_width ""2""
cl_crosshairalpha ""255""
cl_crosshaircolor ""1""
cl_crosshaircolor_b ""255""
cl_crosshaircolor_g ""0""
cl_crosshaircolor_r ""255""
cl_crosshairdot ""0""
cl_crosshairgap ""-2""
cl_crosshairgap_useweaponvalue ""0""
cl_crosshairscale ""4""
cl_crosshairsize ""3""
cl_crosshairstyle ""4""
cl_crosshairthickness ""1""
cl_crosshairusealpha ""1""
cl_fixedcrosshairgap ""-4.5"""
        Me.Text = "Crosshair selector window - selected: tabseN"
    End Sub

    Private Sub picfugly_Click(sender As Object, e As EventArgs) Handles picfugly.Click
        crosshair = "cl_crosshair_drawoutline ""1""
cl_crosshair_dynamic_maxdist_splitratio ""0.35""
cl_crosshair_dynamic_splitalpha_innermod ""1""
cl_crosshair_dynamic_splitalpha_outermod ""0.5""
cl_crosshair_dynamic_splitdist ""7""
cl_crosshair_outlinethickness ""1""
cl_crosshair_sniper_width ""2""
cl_crosshairalpha ""300""
cl_crosshaircolor ""4""
cl_crosshaircolor_b ""255""
cl_crosshaircolor_g ""0""
cl_crosshaircolor_r ""255""
cl_crosshairdot ""0""
cl_crosshairgap ""-1""
cl_crosshairgap_useweaponvalue ""0""
cl_crosshairscale ""4""
cl_crosshairsize ""3.5""
cl_crosshairstyle ""5""
cl_crosshairthickness ""1.5""
cl_crosshairusealpha ""1""
cl_fixedcrosshairgap ""-4.5"""
        Me.Text = "Crosshair selector window - selected: FugLy"
    End Sub

    Private Sub pichooch_Click(sender As Object, e As EventArgs) Handles pichooch.Click
        crosshair = "cl_crosshair_drawoutline ""0""
cl_crosshair_dynamic_maxdist_splitratio ""0.35""
cl_crosshair_dynamic_splitalpha_innermod ""1""
cl_crosshair_dynamic_splitalpha_outermod ""0.5""
cl_crosshair_dynamic_splitdist ""7""
cl_crosshair_outlinethickness ""1""
cl_crosshair_sniper_width ""2""
cl_crosshairalpha ""255""
cl_crosshaircolor ""1""
cl_crosshaircolor_b ""50""
cl_crosshaircolor_g ""250""
cl_crosshaircolor_r ""50""
cl_crosshairdot """"0""
cl_crosshairgap ""0""
cl_crosshairgap_useweaponvalue ""0""
cl_crosshairscale ""4""
cl_crosshairsize ""1""
cl_crosshairstyle ""4""
cl_crosshairthickness ""0""
cl_crosshairusealpha ""1""
cl_fixedcrosshairgap ""3"""
        Me.Text = "Crosshair selector window - selected: hooch"
    End Sub

    Private Sub picdosia_Click(sender As Object, e As EventArgs) Handles picdosia.Click
        crosshair = "cl_crosshair_drawoutline ""0""
cl_crosshair_dynamic_maxdist_splitratio ""0.35""
cl_crosshair_dynamic_splitalpha_innermod ""1""
cl_crosshair_dynamic_splitalpha_outermod ""0.5""
cl_crosshair_dynamic_splitdist ""7""
cl_crosshair_outlinethickness ""1""
cl_crosshair_sniper_width ""2""
cl_crosshairalpha ""999""
cl_crosshaircolor ""1""
cl_crosshaircolor_b ""50""
cl_crosshaircolor_g ""250""
cl_crosshaircolor_r ""50""
cl_crosshairdot ""0""
cl_crosshairgap ""-3""
cl_crosshairgap_useweaponvalue ""0""
cl_crosshairscale ""4""
cl_crosshairsize ""1""
cl_crosshairstyle ""4""
cl_crosshairthickness ""0.5""
cl_crosshairusealpha ""1""
cl_fixedcrosshairgap ""3"""
        Me.Text = "Crosshair selector window - selected: Dosia"
    End Sub

    Private Sub picmou_Click(sender As Object, e As EventArgs) Handles picmou.Click
        crosshair = "cl_crosshair_drawoutline ""0""
cl_crosshair_dynamic_maxdist_splitratio ""0.35""
cl_crosshair_dynamic_splitalpha_innermod ""1""
cl_crosshair_dynamic_splitalpha_outermod ""0.5""
cl_crosshair_dynamic_splitdist ""7""
cl_crosshair_outlinethickness ""1""
cl_crosshair_sniper_width ""2""
cl_crosshairalpha ""200""
cl_crosshaircolor ""1""
cl_crosshaircolor_b ""50""
cl_crosshaircolor_g ""250""
cl_crosshaircolor_r ""50""
cl_crosshairdot ""0""
cl_crosshairgap ""1""
cl_crosshairgap_useweaponvalue ""0""
cl_crosshairscale ""4""
cl_crosshairsize ""3""
cl_crosshairstyle ""2""
cl_crosshairthickness ""1""
cl_crosshairusealpha ""1""
cl_fixedcrosshairgap ""3"""
        Me.Text = "Crosshair selector window - selected: mou"
    End Sub

    Private Sub picAdren_Click(sender As Object, e As EventArgs) Handles picAdren.Click
        crosshair = "cl_crosshair_drawoutline ""0""
cl_crosshair_dynamic_maxdist_splitratio ""0.35""
cl_crosshair_dynamic_splitalpha_innermod ""1""
cl_crosshair_dynamic_splitalpha_outermod ""0.5""
cl_crosshair_dynamic_splitdist ""7""
cl_crosshair_outlinethickness ""1""
cl_crosshair_sniper_width ""2""
cl_crosshairalpha ""255""
cl_crosshaircolor ""1""
cl_crosshaircolor_b ""50""
cl_crosshaircolor_g ""250""
cl_crosshaircolor_r ""50""
cl_crosshairdot ""0""
cl_crosshairgap ""-1.5""
cl_crosshairgap_useweaponvalue ""0""
cl_crosshairscale ""4""
cl_crosshairsize ""3""
cl_crosshairstyle ""4""
cl_crosshairthickness ""1""
cl_crosshairusealpha ""1""
cl_fixedcrosshairgap ""3"""
        Me.Text = "Crosshair selector window - selected: AdreN"
    End Sub

    Private Sub picspaze_Click(sender As Object, e As EventArgs) Handles picspaze.Click
        crosshair = "cl_crosshair_drawoutline ""0""
cl_crosshair_dynamic_maxdist_splitratio ""0.35""
cl_crosshair_dynamic_splitalpha_innermod ""1""
cl_crosshair_dynamic_splitalpha_outermod ""0.5""
cl_crosshair_dynamic_splitdist ""7""
cl_crosshair_outlinethickness ""1""
cl_crosshair_sniper_width ""2""
cl_crosshairalpha ""255""
cl_crosshaircolor ""1""
cl_crosshaircolor_b ""50""
cl_crosshaircolor_g ""250""
cl_crosshaircolor_r ""50""
cl_crosshairdot ""0""
cl_crosshairgap ""-2""
cl_crosshairgap_useweaponvalue ""0""
cl_crosshairscale ""4""
cl_crosshairsize ""2""
cl_crosshairstyle ""4""
cl_crosshairthickness ""0""
cl_crosshairusealpha ""1""
cl_fixedcrosshairgap ""3"""
        Me.Text = "Crosshair selector window - selected: spaze"
    End Sub

    Private Sub picblade_Click(sender As Object, e As EventArgs) Handles picblade.Click
        crosshair = "cl_crosshair_drawoutline ""1""
cl_crosshair_dynamic_maxdist_splitratio ""0.35""
cl_crosshair_dynamic_splitalpha_innermod ""1""
cl_crosshair_dynamic_splitalpha_outermod ""0.5""
cl_crosshair_dynamic_splitdist ""7""
cl_crosshair_outlinethickness ""0.1""
cl_crosshair_sniper_width ""2""
cl_crosshairalpha ""255""
cl_crosshaircolor ""5""
cl_crosshaircolor_b ""230""
cl_crosshaircolor_g ""170""
cl_crosshaircolor_r ""100""
cl_crosshairdot ""0""
cl_crosshairgap ""-2""
cl_crosshairgap_useweaponvalue ""0""
cl_crosshairscale ""4""
cl_crosshairsize ""5""
cl_crosshairstyle ""5""
cl_crosshairthickness ""0.5""
cl_crosshairusealpha ""1""
cl_fixedcrosshairgap ""3"""
        Me.Text = "Crosshair selector window - selected: B1ad3"
    End Sub

    Private Sub picwe_Click(sender As Object, e As EventArgs) Handles picwe.Click
        crosshair = "cl_crosshair_drawoutline ""0""
cl_crosshair_dynamic_maxdist_splitratio ""0.35""
cl_crosshair_dynamic_splitalpha_innermod ""1""
cl_crosshair_dynamic_splitalpha_outermod ""0.5""
cl_crosshair_dynamic_splitdist ""7""
cl_crosshair_outlinethickness ""0.5""
cl_crosshair_sniper_width ""2""
cl_crosshairalpha ""255""
cl_crosshaircolor ""4""
cl_crosshaircolor_b ""230""
cl_crosshaircolor_g ""170""
cl_crosshaircolor_r ""100""
cl_crosshairdot ""0""
cl_crosshairgap ""0""
cl_crosshairgap_useweaponvalue ""0""
cl_crosshairscale ""4""
cl_crosshairsize ""3""
cl_crosshairstyle ""5""
cl_crosshairthickness ""0""
cl_crosshairusealpha ""1""
cl_fixedcrosshairgap ""3"""
        Me.Text = "Crosshair selector window - selected: WorldEdit"
    End Sub

    Private Sub picmarkeloff_Click(sender As Object, e As EventArgs) Handles picmarkeloff.Click
        crosshair = "cl_crosshair_drawoutline ""0""
cl_crosshair_dynamic_maxdist_splitratio ""0.35""
cl_crosshair_dynamic_splitalpha_innermod ""1""
cl_crosshair_dynamic_splitalpha_outermod ""0.5""
cl_crosshair_dynamic_splitdist ""7""
cl_crosshair_outlinethickness ""1""
cl_crosshair_sniper_width ""2""
cl_crosshairalpha ""8888""
cl_crosshaircolor ""1""
cl_crosshaircolor_b ""0""
cl_crosshaircolor_g ""0""
cl_crosshaircolor_r ""250""
cl_crosshairdot ""0""
cl_crosshairgap ""-3""
cl_crosshairgap_useweaponvalue ""0""
cl_crosshairscale ""4""
cl_crosshairsize ""4""
cl_crosshairstyle ""4""
cl_crosshairthickness ""0.5""
cl_crosshairusealpha ""1""
cl_fixedcrosshairgap ""3"""
        Me.Text = "Crosshair selector window - selected: markeloff"
    End Sub

    Private Sub picwl_Click(sender As Object, e As EventArgs) Handles picwl.Click
        crosshair = "cl_crosshair_drawoutline ""0""
cl_crosshair_dynamic_maxdist_splitratio ""0.35""
cl_crosshair_dynamic_splitalpha_innermod ""1""
cl_crosshair_dynamic_splitalpha_outermod ""0.5""
cl_crosshair_dynamic_splitdist ""7""
cl_crosshair_outlinethickness ""1""
cl_crosshair_sniper_width ""2""
cl_crosshairalpha ""500""
cl_crosshaircolor ""5""
cl_crosshaircolor_b ""0""
cl_crosshaircolor_g ""0""
cl_crosshaircolor_r ""0""
cl_crosshairdot ""0""
cl_crosshairgap ""-3""
cl_crosshairgap_useweaponvalue ""0""
cl_crosshairscale ""4""
cl_crosshairsize ""2.4""
cl_crosshairstyle ""4""
cl_crosshairthickness ""1""
cl_crosshairusealpha ""1""
cl_fixedcrosshairgap ""3"""
        Me.Text = "Crosshair selector window - selected: wayLander"
    End Sub

    Private Sub picangel_Click(sender As Object, e As EventArgs) Handles picangel.Click
        crosshair = "cl_crosshair_drawoutline ""1""
cl_crosshair_dynamic_maxdist_splitratio ""0.35""
cl_crosshair_dynamic_splitalpha_innermod ""1""
cl_crosshair_dynamic_splitalpha_outermod ""0.5""
cl_crosshair_dynamic_splitdist ""7""
cl_crosshair_outlinethickness ""0.1""
cl_crosshair_sniper_width ""2""
cl_crosshairalpha ""200""
cl_crosshaircolor ""red""
cl_crosshaircolor_b ""50""
cl_crosshaircolor_g ""250""
cl_crosshaircolor_r ""50""
cl_crosshairdot ""0""
cl_crosshairgap ""-2""
cl_crosshairgap_useweaponvalue ""0""
cl_crosshairscale ""4""
cl_crosshairsize ""2""
cl_crosshairstyle ""4""
cl_crosshairthickness ""0""
cl_crosshairusealpha ""1""
cl_fixedcrosshairgap ""3"""
        Me.Text = "Crosshair selector window - selected: ANGE1"
    End Sub

    Private Sub picstyko_Click(sender As Object, e As EventArgs) Handles picstyko.Click
        crosshair = "cl_crosshair_drawoutline ""0""
cl_crosshair_dynamic_maxdist_splitratio ""0.35""
cl_crosshair_dynamic_splitalpha_innermod ""1""
cl_crosshair_dynamic_splitalpha_outermod ""0.5""
cl_crosshair_dynamic_splitdist ""7""
cl_crosshair_outlinethickness ""1""
cl_crosshair_sniper_width ""2""
cl_crosshairalpha ""300""
cl_crosshaircolor ""1""
cl_crosshaircolor_b ""50""
cl_crosshaircolor_g ""250""
cl_crosshaircolor_r ""50""
cl_crosshairdot ""0""
cl_crosshairgap ""-1""
cl_crosshairgap_useweaponvalue ""0""
cl_crosshairscale ""4""
cl_crosshairsize ""2.5""
cl_crosshairstyle ""4""
cl_crosshairthickness ""0""
cl_crosshairusealpha ""1""
cl_fixedcrosshairgap ""3"""
        Me.Text = "Crosshair selector window - selected: STYKO"
    End Sub

    Private Sub piczero_Click(sender As Object, e As EventArgs) Handles piczero.Click
        crosshair = "cl_crosshair_drawoutline ""0""
cl_crosshair_dynamic_maxdist_splitratio ""0.35""
cl_crosshair_dynamic_splitalpha_innermod ""1""
cl_crosshair_dynamic_splitalpha_outermod ""0.5""
cl_crosshair_dynamic_splitdist ""7""
cl_crosshair_outlinethickness ""1""
cl_crosshair_sniper_width ""2""
cl_crosshairalpha ""255""
cl_crosshaircolor ""4""
cl_crosshaircolor_b ""50""
cl_crosshaircolor_g ""250""
cl_crosshaircolor_r ""50""
cl_crosshairdot ""0""
cl_crosshairgap ""0""
cl_crosshairgap_useweaponvalue ""0""
cl_crosshairscale ""4""
cl_crosshairsize ""4.5""
cl_crosshairstyle ""4""
cl_crosshairthickness ""1.5""
cl_crosshairusealpha ""1""
cl_fixedcrosshairgap ""3"""
        Me.Text = "Crosshair selector window - selected: ZERO"
    End Sub
    Private Sub picbondik_Click(sender As Object, e As EventArgs) Handles picbondik.Click
        crosshair = "cl_crosshair_drawoutline ""0""
cl_crosshair_dynamic_maxdist_splitratio ""0.35""
cl_crosshair_dynamic_splitalpha_innermod ""1""
cl_crosshair_dynamic_splitalpha_outermod ""0.5""
cl_crosshair_dynamic_splitdist ""7""
cl_crosshair_outlinethickness ""0.1""
cl_crosshair_sniper_width ""2""
cl_crosshairalpha ""255""
cl_crosshaircolor ""1""
cl_crosshaircolor_b ""50""
cl_crosshaircolor_g ""250""
cl_crosshaircolor_r ""50""
cl_crosshairdot ""0""
cl_crosshairgap ""-1""
cl_crosshairgap_useweaponvalue ""0""
cl_crosshairscale ""4""
cl_crosshairsize ""2""
cl_crosshairstyle ""4""
cl_crosshairthickness ""1""
cl_crosshairusealpha ""1""
cl_fixedcrosshairgap ""3"""
        Me.Text = "Crosshair selector window - selected: bondik"
    End Sub

    Private Sub picShara_Click(sender As Object, e As EventArgs) Handles picShara.Click
        crosshair = "cl_crosshair_drawoutline ""0""
cl_crosshair_dynamic_maxdist_splitratio ""0.35""
cl_crosshair_dynamic_splitalpha_innermod ""1""
cl_crosshair_dynamic_splitalpha_outermod ""0.5""
cl_crosshair_dynamic_splitdist ""7""
cl_crosshair_outlinethickness ""0.1""
cl_crosshair_sniper_width ""2""
cl_crosshairalpha ""255""
cl_crosshaircolor ""4""
cl_crosshaircolor_b ""50""
cl_crosshaircolor_g ""250""
cl_crosshaircolor_r ""50""
cl_crosshairdot ""0""
cl_crosshairgap ""-1""
cl_crosshairgap_useweaponvalue ""0""
cl_crosshairscale ""4""
cl_crosshairsize ""2""
cl_crosshairstyle ""1""
cl_crosshairthickness ""1""
cl_crosshairusealpha ""1""
cl_fixedcrosshairgap ""3"""
        Me.Text = "Crosshair selector window - selected: Shara"
    End Sub

    Private Sub Crosshair_selector_FormClosing(sender As Object, e As FormClosingEventArgs) Handles Me.FormClosing
        If crosshair = "" Then
            If MsgBox("You have not chosen any crosshair from the list." & vbLf & "Would you like to close anyway?", MsgBoxStyle.YesNo, "No selection") = MsgBoxResult.No Then
                e.Cancel = True
                Correction.Start()
            End If
        End If
    End Sub
End Class